font_family FiraCode Nerd Font

cursor_trail 3
# cursor_shape underline
# cursor_shape block

# 强制保持光标形状，禁止程序更改
# shell_integration no-cursor

# 窗口大小
initial_window_width 800
initial_window_height 900

# 行间距
adjust_line_height 120%

# 字体大小
font_size 24
# font_family Nerd Font Mono

# 隐藏标题栏
# hide_window_decorations titlebar-only


# background_image ~/Pictures/Wallpaper/【哲风壁纸】云-天空-插图.png

# background_opacity 0.8
# background #000000

background_image_layout scaled





