

# 标签页管理
# Ctrl+n: 切换到下一个标签页
map ctrl+n next_tab
# Ctrl+p: 切换到上一个标签页
map ctrl+p previous_tab
# Ctrl+t: 新建标签页
map ctrl+t new_tab
# Ctrl+w: 关闭当前标签页
map alt+w close_window




# 分屏管理
# Ctrl+%: 水平分屏（上下分）
map ctrl+% launch --location=hsplit
# Ctrl+": 垂直分屏（左右分）



# 窗格导航（切换焦点分屏）
# Ctrl+h: 向左切换
map ctrl+h neighboring_window left
# Ctrl+j: 向下切换
map ctrl+j neighboring_window down
# Ctrl+k: 向上切换
map ctrl+k neighboring_window up
# Ctrl+l: 向右切换
map ctrl+l neighboring_window right



