;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8-emacs; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("org-capture-last-stored"
  (filename . "~/roam-notes/20260912214229-test.org")
  (front-context-string)
  (rear-context-string . ":\n#+title: test\n")
  (position . 82)
  (last-modified 27301 22221 522025 426000))
)
