;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8-emacs; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("org-capture-last-stored"
  (filename . "~/roam-notes/20260912183624-今日笔记.org")
  (front-context-string . "\n今日无事，八点多床，后面赖床到")
  (rear-context-string . ":\n#+title: 今日笔记\n")
  (position . 82)
  (last-modified 27301 11129 841585 655000))
)
