# 处理nvim颜色问题
set-option -sa terminal-overrides ",xterm*:Tc"

# 鼠标支持
set -g mouse on

# 修改前缀prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix


# 让窗口数字从1开始
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on



## binds
bind-key -n C-b send-keys Left      # Ctrl + b = 光标左移
bind-key -n C-f send-keys Right     # Ctrl + f = 光标右移
bind-key -n C-h send-keys Backspace   # Ctrl + h = 删除左边一个字符（退格）
bind-key -n C-a send-keys Home      # Ctrl + a → 跳到行首
bind-key -n C-e send-keys End       # Ctrl + e → 跳到行尾

# -n参数是跳过前缀执行，不用c-b，直接c
# 前一个窗口
bind -n M-H previous-window
bind -n M-L next-window

## ----------------------------------------------

# 使用前先加载插件，要手动加载profix+I
# 插件管理器
set -g @plugin 'tmux-plugins/tpm'
# 设置了一些选项，用来修复tmux基础配置中的一些古怪问题
set -g @plugin 'tmux-plugins/tmux-sensible'
# 与neovim的集成，让它能用c-hjkl移动
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
# # 下方绿色标题栏主题
# set -g @plugin 'catppuccin/tmux'
# # 修改主题颜色
# set -g @catppuccin_flavour 'latte'


run '~/.config/tmux/plugins/tpm/tpm'


